mod _algo_traits;
pub use _algo_traits::AssignStorageSiteTrait;
pub use _algo_traits::HasIngestCapacityTrait;

pub mod circular_algo;
pub use circular_algo::Algo as CircularAlgo;
pub mod compressing_algo;
pub use compressing_algo::Algo as CompressingAlgo;
pub mod steady_algo;
pub use steady_algo::Algo as SteadyAlgo;
pub mod sticky_algo;
pub use sticky_algo::Algo as StickyAlgo;
pub mod stretched_algo;
pub use stretched_algo::Algo as StretchedAlgo;
pub mod tilted_algo;
pub use tilted_algo::Algo as TiltedAlgo;

pub mod hybrid_0_circular_2_steady_3_algo;
pub use hybrid_0_circular_2_steady_3_algo::Algo as Hybrid0Circular2Steady3Algo;
pub mod hybrid_0_circular_2_tilted_3_algo;
pub use hybrid_0_circular_2_tilted_3_algo::Algo as Hybrid0Circular2Tilted3Algo;
pub mod hybrid_0_circular_3_steady_4_algo;
pub use hybrid_0_circular_3_steady_4_algo::Algo as Hybrid0Circular3Steady4Algo;
pub mod hybrid_0_circular_5_steady_6_algo;
pub use hybrid_0_circular_5_steady_6_algo::Algo as Hybrid0Circular5Steady6Algo;
pub mod hybrid_0_circular_7_steady_8_algo;
pub use hybrid_0_circular_7_steady_8_algo::Algo as Hybrid0Circular7Steady8Algo;
pub mod hybrid_0_circular_11_steady_12_algo;
pub use hybrid_0_circular_11_steady_12_algo::Algo as Hybrid0Circular11Steady12Algo;
pub mod hybrid_0_steady_1_circular_2_algo;
pub use hybrid_0_steady_1_circular_2_algo::Algo as Hybrid0Steady1Circular2Algo;
pub mod hybrid_0_steady_1_stretched_2_algo;
pub use hybrid_0_steady_1_stretched_2_algo::Algo as Hybrid0Steady1Stretched2Algo;
pub mod hybrid_0_steady_1_tilted_2_algo;
pub use hybrid_0_steady_1_tilted_2_algo::Algo as Hybrid0Steady1Tilted2Algo;
pub mod hybrid_0_steady_1_tilted_2_circular_3_algo;
pub use hybrid_0_steady_1_tilted_2_circular_3_algo::Algo as Hybrid0Steady1Tilted2Circular3Algo;
pub mod hybrid_0_steady_2_circular_3_algo;
pub use hybrid_0_steady_2_circular_3_algo::Algo as Hybrid0Steady2Circular3Algo;
pub mod hybrid_0_steady_2_tilted_3_algo;
pub use hybrid_0_steady_2_tilted_3_algo::Algo as Hybrid0Steady2Tilted3Algo;
pub mod hybrid_0_tilted_1_circular_2_algo;
pub use hybrid_0_tilted_1_circular_2_algo::Algo as Hybrid0Tilted1Circular2Algo;
pub mod hybrid_0_tilted_2_circular_3_algo;
pub use hybrid_0_tilted_2_circular_3_algo::Algo as Hybrid0Tilted2Circular3Algo;
pub mod hybrid_0_tilted_2_steady_3_algo;
pub use hybrid_0_tilted_2_steady_3_algo::Algo as Hybrid0Tilted2Steady3Algo;
