#pragma once
#ifndef DOWNSTREAM_AUXLIB_DOWNSTREAM_UINT_HPP
#define DOWNSTREAM_AUXLIB_DOWNSTREAM_UINT_HPP

#include <cstdint>

#ifndef DOWNSTREAM_UINT  // allow override
#define DOWNSTREAM_UINT std::uint64_t
#endif  // DOWNSTREAM_UINT

#endif  // DOWNSTREAM_AUXLIB_DOWNSTREAM_UINT_HPP
