site_name: downstream
theme:
  name: material
nav:
  - Home: index.md
  - Python Quickstart: quickstart.md
  - Selecting a downstream Algorithm: algorithm.md
  - Python API Reference: python.md
  - C++ API Reference: cpp.md
  - Rust API Reference: rust.md
  - CSL API Reference: csl.md
  - Zig API Reference: zig.md
  - Publications and Presentations: publications.md
  - Projects Using downstream: projects.md
  - Citing: citing.md
  - Contributing: contributing.md
  - Credits: credits.md
  - Glossary: glossary.md

plugins:
  - search
  - include-markdown
  - mkdocstrings:
      handlers:
        python:
          paths: [../python/downstream/dstream]
          options:
            docstring_style: numpy
            show_root_heading: true
            heading_level: 1

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
