site_name: downstream
theme:
  name: material
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Selecting a downstream Algorithm: algorithm.md
  - Python Reference: python.md
  - C++ Reference: cpp.md
  - Rust Reference: rust.md
  - CSL Reference: csl.md
  - Zig Reference: zig.md
  - Publications and Presentations: publications.md
  - Projects Using downstream: projects.md
  - Citing: citing.md
  - Contributing: contributing.md
  - Credits: credits.md
  - Glossary: glossary.md

plugins:
  - search
  - include-markdown
  - mkdocstrings:
      handlers:
        python:
          paths:
            - ../python/downstream/dataframe
            - ../python/downstream/dstream
            - ../python/downstream/dsurf
          options:
            docstring_style: numpy
            show_root_heading: true
            heading_level: 3

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
