name: CI
on:
  push:
    branches: [ "master", "gh-pages" ]
  workflow_dispatch:
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          cd docs
          python -m pip install --upgrade pip
          python -m pip install --upgrade uv
          uv pip install -r requirements.txt --system
      - name: Deploy
        run: |
          cd docs
          mkdocs gh-deploy
          git add -A
          git commit -m "Deploy documentation"
