name: CI
on:
  push:
    branches: [ "master", "gh-pages" ]
  workflow_dispatch:
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          cd docs
          python -m pip install --upgrade pip
          python -m pip install --upgrade uv
          uv pip install -r requirements.txt --system
      - name: Initialize submodules
        run: |
          git submodule update --init --recursive
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Deploy
        run: |
          cd docs
          mkdocs gh-deploy --force
          git add -A
          git commit -m "Deploy documentation"
