name: CI
on:
  push:
    branches: [ "master", "gh-pages" ]
  workflow_dispatch:
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          cd docs
          python -m pip install --upgrade pip
          python -m pip install --upgrade uv
          uv pip install -r requirements.txt --system
      - run: |
          mkdocs gh-deploy
          git add -A
          git commit -m "Deploy documentation"
